export const headshotPortraits = [
  ["woman_10", "nature"],
  ["man_02", "office"],
  ["woman_06", "city"],
  ["man_10", "studio"],
  ["woman_01", "office"],
  ["man_04", "nature"],
  ["woman_07", "studio"],
  ["man_06", "city"],
  ["woman_04", "nature"],
  ["man_01", "studio"],
  ["woman_02", "city"],
  ["man_07", "office"],
  ["woman_03", "studio"],
  ["man_08", "nature"],
  ["woman_05", "office"],
  ["man_03", "city"],
  ["woman_08", "nature"],
  ["man_05", "studio"],
  ["woman_09", "office"],
  ["man_09", "city"],
].map(([id, background]) => ({
  id,
  casual: `/headshots/${id}_casual.webp`,
  professional: `/headshots/${id}_professional_${background}.webp`,
}));
