export const en = {
  meta: {
    title: "Perfilisto: A profile that's ready to send",
    description:
      "Perfilisto helps you turn your work, skills, and story into one clean page you can share with recruiters, clients, and anyone who needs to know what you do.",
    siteName: "Perfilisto",
  },
  brand: {
    name: "Perfilisto",
    homeAriaLabel: "Perfilisto home",
  },
  nav: {
    howItWorks: "How it works",
    pricing: "Pricing",
    login: "Login",
    getStarted: "Get started",
    dashboard: "Dashboard",
  },
  hero: {
    badge: "#1 🇪🇸 Spanish AI headshot",
    titleTint: "Studio-quality",
    titleLine1: "headshots.",
    titleLine2: "From your selfies.",
    description:
      "Skip the 300€ photographer. Turn your selfies into studio-quality headshots in 30 minutes.",
    cta: "Create my headshots",
    supportingText: "Your photos stay private",
    rating: "4.8/5",
    ratingLabel: "Rated 4.8 out of 5",
    trustText: "Trusted by +1453 professionals",
    beforeLabel: "Your selfies",
    afterLabel: "Professional headshots",
    generatedBadge: "AI generated by Perfilisto",
  },
  howItWorks: {
    titleBefore: "Get your headshots in",
    titleTint: "minutes",
    titleAfter: ", not days",
    subtitle: "It's as easy as 1–2–3–4.",
    uploaded: "Uploaded successfully",
    outfits: ["Professional", "Business casual", "Smart casual"],
    steps: [
      {
        number: "1",
        title: "Select your attire and backgrounds",
        body: "Choose from curated outfits and backdrops for LinkedIn, your CV, and your website.",
      },
      {
        number: "2",
        title: "Upload a few photos of yourself",
        body: "Selfies work. Six clear shots of your face is enough — quality over quantity.",
      },
      {
        number: "3",
        title: "We generate your personalized AI headshots",
        body: "Perfilisto builds the set. We email you when they're ready.",
      },
      {
        number: "4",
        title: "View, edit, and download your favorites",
        body: "Pick the shots you want and use them on LinkedIn, your CV, or your site.",
      },
    ],
  },
  clients: {
    titleBefore: "Our clients",
    titleTint: "trust us",
    subtitle: "Full before-and-afters, with a few words from the people in the photos.",
    before: "Before",
    after: "After",
  },
  compare: {
    titleBefore: "Compare Perfilisto to hiring a",
    titleTint: "corporate photographer",
    subtitle: "Same job. Less calendar, less travel, less than a studio session.",
    perfilisto: "With Perfilisto",
    photographer: "Hiring a photographer",
    rows: [
      {
        label: "Do it from home",
        perfilisto: "Yes",
        photographer: "No, on-location shoot",
      },
      {
        label: "Time",
        perfilisto: "As quick as 30 min",
        photographer: "2–3 work days",
      },
      {
        label: "Number of headshots",
        perfilisto: "A full gallery",
        photographer: "5–10 per person",
      },
      {
        label: "Outfits",
        perfilisto: "Multiple looks",
        photographer: "1–2 outfits",
      },
      {
        label: "Backgrounds",
        perfilisto: "Your choice",
        photographer: "1 background",
      },
      {
        label: "Visual consistency",
        perfilisto: "Yes, same look across shots",
        photographer: "Manual edits needed",
      },
    ],
  },
  pricing: {
    titleBefore: "Simple and",
    titleTint: "transparent",
    titleAfter: "prices",
    subtitle:
      "The average cost of professional photos is 300€ in the EU. Perfilisto starts at 29€ — up to 10 times cheaper than a studio session.",
    guarantee: "100% money-back guarantee",
    popular: "Popular",
    currency: "€",
    period: "one-time",
    plans: [
      {
        name: "Basic",
        price: "29",
        description: "Get 10 photos with unique backgrounds and outfits.",
        cta: "Get 10 photos in 3 hours",
        note: "29€ due today. Photos in 3 hours.",
        featured: false,
        features: [
          "Delivery time: 3 hours",
          "10 photos",
          "Unique backgrounds and outfits",
        ],
      },
      {
        name: "Professional",
        price: "39",
        description: "Get 100 photos with unique backgrounds and outfits.",
        cta: "Get 100 photos in 2 hours",
        note: "39€ due today. 100% money-back guarantee.",
        featured: true,
        features: [
          "Delivery time: 2 hours",
          "100 photos",
          "Unique backgrounds and outfits",
        ],
      },
      {
        name: "Executive",
        price: "59",
        description: "Get 200 photos with unique backgrounds and outfits.",
        cta: "Get 200 photos in 1 hour",
        note: "59€ due today. Photos in 1 hour.",
        featured: false,
        features: [
          "Delivery time: 1 hour",
          "200 photos",
          "Unique backgrounds and outfits",
        ],
      },
    ],
  },
  faq: {
    title: "Frequently asked",
    items: [
      {
        question: "What is Perfilisto?",
        answer:
          "Perfilisto turns a few selfies into studio-quality headshots. You pick outfits and backgrounds, upload your photos, and get a gallery back.",
      },
      {
        question: "How many photos do I need to upload?",
        answer:
          "Six clear shots of your face is enough. Selfies work. Quality matters more than quantity.",
      },
      {
        question: "How long does it take?",
        answer:
          "Choosing looks and uploading photos takes about 30 minutes. Delivery is 3 hours on Basic, 2 hours on Professional, and 1 hour on Executive.",
      },
      {
        question: "Can I use these photos on LinkedIn, my CV, and my website?",
        answer:
          "Yes. That's what they're for. Download the shots you want and use them wherever you need a professional photo.",
      },
      {
        question: "Are my photos private?",
        answer:
          "Yes. Your uploads stay private. Result photos are labeled as AI generated by Perfilisto.",
      },
      {
        question: "What if I don't like the results?",
        answer:
          "The Professional plan includes a 100% money-back guarantee.",
      },
      {
        question: "How is this different from hiring a photographer?",
        answer:
          "No studio and no appointment. You do it from home, pick multiple outfits and backgrounds, and get a full gallery instead of 5–10 shots from one session.",
      },
      {
        question: "Are the photos AI generated?",
        answer:
          "Yes. The result photos are AI generated by Perfilisto. We show that on the images.",
      },
    ],
  },
  footer: {
    tagline: "Studio-quality headshots from your selfies.",
    explore: "Explore",
    company: "Company",
    howItWorks: "How it works",
    pricing: "Pricing",
    faq: "FAQ",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "Perfilisto · TAP & SWIPE SAS",
    privacyPolicy: "Privacy policy",
  },
  legal: {
    privacy: {
      title: "Privacy",
      updated: "Last updated September 10, 2026",
      body: [
        "Perfilisto is a headshot product from Tap & Swipe SAS. This page describes what we intend to collect once accounts are live.",
        "If you create headshots, we store the photos you upload and the results we generate so we can deliver your gallery.",
        "If you create an account, we store your email so you can sign back in.",
        "We do not sell personal data. Result photos are labeled as AI generated.",
        "You can ask us to delete your account and photos by writing to hello@perfilisto.com.",
      ],
    },
    terms: {
      title: "Terms",
      updated: "Last updated September 10, 2026",
      body: [
        "By using Perfilisto, you agree to these terms.",
        "You are responsible for the photos you upload. Only upload pictures of yourself that you have the right to use.",
        "Result photos are AI generated. The Professional plan includes a 100% money-back guarantee.",
        "We may change the product, pricing, or these terms. If a change is material, we will update this page.",
        "The service is provided by Tap & Swipe SAS. These terms are governed by the laws of France.",
      ],
    },
  },
} as const;

export type Messages = typeof en;
