import plans from "@/lib/orders/plans.json";

export const en = {
  meta: {
    title: "AI Headshot Generator for Professional Photos | Perfilisto",
    description:
      "Turn your selfies into professional AI headshots for LinkedIn, your CV, and company profiles. Create a complete gallery from home with Perfilisto.",
    siteName: "Perfilisto",
  },
  brand: {
    name: "Perfilisto",
    homeAriaLabel: "Perfilisto home",
  },
  nav: {
    howItWorks: "How it works",
    pricing: "Pricing",
    login: "Login",
    getStarted: "Get started",
    dashboard: "Dashboard",
  },
  login: {
    title: "Welcome back",
    description: "Your next great first impression is waiting.",
    google: "Continue with Google",
    facebook: "Continue with Facebook",
    unavailable: "Sign-in will be available soon.",
    newHere: "New to Perfilisto?",
    getStarted: "Create your headshots",
    termsPrefix: "By continuing, you agree to our",
    terms: "Terms of Service",
    and: "and",
    privacy: "Privacy Policy",
    previewTitle: "Look like your next opportunity.",
    previewDescription: "Professional headshots. Made from your selfies.",
  },
  hero: {
    badge: "#1 🇪🇸 Spanish AI headshot",
    titleTint: "Studio-quality",
    titleLine1: "headshots.",
    titleLine2: "From your selfies.",
    description:
      "Skip the 300€ photographer. Turn your selfies into studio-quality headshots in as little as 15 minutes.",
    cta: "Create my headshots",
    supportingText: "Your photos stay private",
    rating: "4.8/5",
    ratingLabel: "Rated 4.8 out of 5",
    trustText: "Trusted by +1453 professionals",
    beforeLabel: "Your selfies",
    afterLabel: "Professional headshots",
    generatedBadge: "AI generated by Perfilisto",
  },
  howItWorks: {
    titleBefore: "Get your headshots in as little as",
    titleTint: "15 minutes",
    titleAfter: "",
    subtitle: "It's as easy as 1–2–3–4.",
    uploaded: "Uploaded successfully",
    outfits: ["Professional", "Business casual", "Smart casual"],
    steps: [
      {
        number: "1",
        title: "Select your attire and backgrounds",
        body: "Choose from curated outfits and backdrops for LinkedIn, your CV, and your website.",
      },
      {
        number: "2",
        title: "Upload a few photos of yourself",
        body: "Selfies work. Six clear shots of your face is enough — quality over quantity.",
      },
      {
        number: "3",
        title: "We generate your personalized AI headshots",
        body: "Perfilisto builds the set. We email you when they're ready.",
      },
      {
        number: "4",
        title: "View, edit, and download your favorites",
        body: "Pick the shots you want and use them on LinkedIn, your CV, or your site.",
      },
    ],
  },
  clients: {
    titleBefore: "Our clients",
    titleTint: "trust us",
    subtitle:
      "Full before-and-afters, with a few words from the people in the photos.",
    before: "Before",
    after: "After",
  },
  compare: {
    titleBefore: "Compare Perfilisto to hiring a",
    titleTint: "corporate photographer",
    subtitle:
      "Same job. Less calendar, less travel, less than a studio session.",
    perfilisto: "With Perfilisto",
    photographer: "Hiring a photographer",
    rows: [
      {
        label: "Do it from home",
        perfilisto: "Yes",
        photographer: "No, on-location shoot",
      },
      {
        label: "Time",
        perfilisto: "As quick as 30 min",
        photographer: "2–3 work days",
      },
      {
        label: "Number of headshots",
        perfilisto: "A full gallery",
        photographer: "5–10 per person",
      },
      {
        label: "Outfits",
        perfilisto: "Multiple looks",
        photographer: "1–2 outfits",
      },
      {
        label: "Backgrounds",
        perfilisto: "Your choice",
        photographer: "1 background",
      },
      {
        label: "Visual consistency",
        perfilisto: "Yes, same look across shots",
        photographer: "Manual edits needed",
      },
    ],
  },
  pricing: {
    titleBefore: "Simple and",
    titleTint: "transparent",
    titleAfter: "prices",
    subtitle:
      "The average cost of professional photos is 300€ in the EU. Perfilisto starts at 29€ — up to 10 times cheaper than a studio session.",
    guarantee: "100% money-back guarantee",
    popular: "Popular",
    currency: "€",
    period: "one-time",
    plans: [
      {
        name: "Basic",
        price: String(plans[0].price),
        description: `Get ${plans[0].photoCount} headshots with unique backgrounds and outfits.`,
        cta: `Get ${plans[0].photoCount} headshots`,
        note: `${plans[0].price}€ due today. Photos within ${plans[0].deliveryTime}.`,
        featured: false,
        features: [
          `Delivery within ${plans[0].deliveryTime}`,
          `${plans[0].photoCount} headshots`,
          "Unique backgrounds and outfits",
        ],
      },
      {
        name: "Professional",
        price: String(plans[1].price),
        description: `Get ${plans[1].photoCount} headshots with unique backgrounds and outfits.`,
        cta: `Get ${plans[1].photoCount} headshots`,
        note: "39€ due today. 100% money-back guarantee.",
        featured: true,
        features: [
          `Delivery within ${plans[1].deliveryTime}`,
          `${plans[1].photoCount} headshots`,
          "Unique backgrounds and outfits",
        ],
      },
      {
        name: "Executive",
        price: String(plans[2].price),
        description: `Get ${plans[2].photoCount} headshots with unique backgrounds and outfits.`,
        cta: `Get ${plans[2].photoCount} headshots`,
        note: `${plans[2].price}€ due today. Photos within ${plans[2].deliveryTime}.`,
        featured: false,
        features: [
          `Delivery within ${plans[2].deliveryTime}`,
          `${plans[2].photoCount} headshots`,
          "Unique backgrounds and outfits",
        ],
      },
    ],
  },
  faq: {
    title: "AI headshot generator FAQs",
    subtitle:
      "Answers about creating professional AI headshots for LinkedIn, your CV, and company profiles with Perfilisto.",
    items: [
      {
        question: "What is an AI headshot generator?",
        answer:
          "An AI headshot generator creates professional portrait photos from selfies you already have. Perfilisto uses your uploaded photos to produce a gallery with studio-style lighting, professional outfits, and polished backgrounds, without a photo shoot.",
      },
      {
        question: "What photos should I upload for the best AI headshots?",
        answer:
          "Upload six clear photos that show your face from different angles, with a few expressions and backgrounds. Selfies are fine. Use good lighting, avoid heavy filters, sunglasses, and group photos, and keep makeup and accessories close to what you normally wear.",
      },
      {
        question: "How long does the AI headshot generator take?",
        answer:
          "Uploading your photos and choosing your looks takes a few minutes. Delivery is within 1 hour for Basic, 30 minutes for Professional, and 15 minutes for Executive.",
      },
      {
        question: "How many AI headshots will I receive?",
        answer:
          "Basic includes 10 headshots, Professional includes 100, and Executive includes 200. Every plan includes a selection of backgrounds and outfits.",
      },
      {
        question: "How realistic are AI-generated professional headshots?",
        answer:
          "Perfilisto aims to create natural, recognizable portraits with professional lighting and backgrounds. AI can occasionally produce an image that looks unusual or misses a detail, which is why you receive a full gallery to choose from. Clear, varied input photos help produce the most realistic results.",
      },
      {
        question: "Can I choose my outfits and backgrounds?",
        answer:
          "Yes. Before uploading your photos, you choose from curated professional outfits and backgrounds so the final gallery suits the way you want to present yourself.",
      },
      {
        question: "Can I use AI headshots on LinkedIn and my CV?",
        answer:
          "Yes. You can use your Perfilisto headshots on LinkedIn, your CV, company profile, portfolio, website, email signature, and other places where you need a professional photo.",
      },
      {
        question: "How much do AI professional headshots cost?",
        answer:
          "Perfilisto is a one-time purchase with plans starting at 29€ for 10 photos. Professional costs 39€ for 50 photos, and Executive costs 59€ for 100 photos. There is no recurring subscription.",
      },
      {
        question: "Can I edit and download my favorites?",
        answer:
          "Yes. When your gallery is ready, you can review the results, edit your favorites, and download the headshots you want to use.",
      },
      {
        question: "Are my selfies and AI headshots private?",
        answer:
          "We store your uploaded photos and generated results so we can create and deliver your gallery. We do not sell your personal data. You can ask us to delete your account and photos at any time by emailing hello@perfilisto.com.",
      },
      {
        question: "What if I don't like the results?",
        answer:
          "The Professional plan includes a 100% money-back guarantee. Following the upload guidance gives the AI the best material to work with and helps produce stronger results.",
      },
      {
        question: "How can I contact Perfilisto?",
        answer:
          "Email hello@perfilisto.com if you need help with an order, your photos, or your account.",
      },
    ],
  },
  footer: {
    tagline: "Studio-quality headshots from your selfies.",
    explore: "Explore",
    company: "Company",
    howItWorks: "How it works",
    pricing: "Pricing",
    faq: "FAQ",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "Perfilisto · TAP & SWIPE SAS",
    privacyPolicy: "Privacy policy",
    dataDeletion: "Data deletion",
  },
  onboarding: {
    welcome: {
      title: "Welcome to Perfilisto",
      subtitle: "Please confirm the following to get started.",
      age: "I confirm that I am of legal majority age and 18+ years old.",
      termsBefore: "I have read, understood, and agree to the",
      termsOfService: "Terms of Service",
      termsAnd: "and",
      privacyPolicy: "Privacy Policy",
      consent:
        "By checking this box, I consent to Perfilisto processing and retaining my photos to generate AI headshots, as described in the Privacy Policy.",
      continue: "Continue",
    },
    shared: {
      back: "Back",
      continue: "Continue",
      skip: "Skip",
      close: "Close",
      subtitle: "Help us generate photos that match your preferences.",
    },
    leave: {
      stat: "4.8/5",
      statLabel: "from +1,453 professionals using Perfilisto",
      title: "Are you sure you want to leave?",
      bodyBefore: "As a special promotional offer, we want to give you",
      offer: "10% off",
      bodyAfter: "your photos. Use the coupon code",
      code: "NEW10",
      bodyEnd: "at checkout.",
      dashboard: "Go to homepage",
      claim: "Claim my discount",
    },
    gender: {
      title: "What's your gender?",
      man: "Man",
      woman: "Woman",
      other: "Other",
    },
    age: {
      title: "How old are you?",
      options: [
        { id: "18-20", label: "18–20" },
        { id: "21-24", label: "21–24" },
        { id: "25-29", label: "25–29" },
        { id: "30-40", label: "30–40" },
        { id: "41-50", label: "41–50" },
        { id: "51-65", label: "51–65" },
        { id: "65+", label: "65+" },
      ],
    },
    hair: {
      title: "What's your hair color?",
      subtitle:
        "If your hair color doesn't match any option exactly, choose the closest match.",
      options: [
        { id: "brown", label: "Brown" },
        { id: "black", label: "Black" },
        { id: "blonde", label: "Blonde" },
        { id: "gray", label: "Gray" },
        { id: "auburn", label: "Auburn" },
        { id: "red", label: "Red" },
        { id: "white", label: "White" },
        { id: "other", label: "Other" },
        { id: "bald", label: "Bald" },
      ],
    },
    hairLength: {
      title: "What's your hair length?",
      subtitle:
        "If your hair length falls between options, choose the closest match.",
      options: [
        { id: "bald", label: "Bald" },
        { id: "buzz", label: "Buzz Cut" },
        { id: "short", label: "Short" },
        { id: "medium", label: "Medium Length" },
        { id: "long", label: "Long" },
      ],
    },
    hairType: {
      title: "What's your hair type?",
      subtitle:
        "If your hair type falls between options, choose the closest match.",
      options: [
        { id: "straight", label: "Straight" },
        { id: "wavy", label: "Wavy" },
        { id: "curly", label: "Curly" },
        { id: "dreadlocks", label: "Dreadlocks" },
      ],
    },
    bodyType: {
      title: "What's your body type?",
      subtitle:
        "If you're between body type options, choose the closest match.",
      options: [
        { id: "slim", label: "Slim" },
        { id: "regular", label: "Regular" },
        { id: "athletic", label: "Athletic" },
        { id: "medium-large", label: "Medium large" },
        { id: "large", label: "Large" },
        { id: "plus-size", label: "Plus Size" },
      ],
    },
    attire: {
      title: "Select your attire",
      subtitle:
        "You'll get an equal mix of results featuring the 3 most popular attires.",
      options: [
        {
          id: "professional",
          label: "Business Professional",
          description: "Formal dress shirts and suits with matching ties",
        },
        {
          id: "business-casual",
          label: "Business Casual",
          description: "Blazers and jackets, long-sleeve shirts",
        },
        {
          id: "smart-casual",
          label: "Smart Casual",
          description:
            "Comfortable sweaters, button-down shirts of varying sleeve lengths",
        },
      ],
    },
    backgrounds: {
      title: "Select your backgrounds",
      subtitle:
        "You'll get an equal mix of results featuring the 4 most popular backgrounds.",
      options: [
        {
          id: "city",
          label: "City",
          description: "Vibrant urban city streets",
        },
        {
          id: "nature",
          label: "Nature",
          description: "Outdoor parks or tree-lined streets",
        },
        {
          id: "office",
          label: "Office",
          description: "Bright, minimalistic corporate office",
        },
        {
          id: "studio",
          label: "Studio",
          description: "Professional photoshoot studio",
        },
      ],
    },
    upload: {
      privacyNotice:
        "As a paid product, we value user privacy and transparency.",
      dropAnywhere: "Drop your photos anywhere",
      dropAnywhereHint:
        "Release to add them to your upload. You can add up to 10 photos.",
      uploadLimitReached: "You’ve added 10 photos",
      removeBeforeUpload: "Remove a photo before adding more.",
      title: "Upload Photos",
      preparingPhotos: "Preparing your photos…",
      tips: [
        "Upload 6–10 photos",
        "Mix of selfies and mid-range shots",
        "Ensure photos are in good lighting",
        "Your photos stay private",
      ],
      computerTitle: "Upload from your computer",
      uploadFiles: "Upload files",
      dropHint: "or drag and drop your photos",
      formats: "PNG, JPG, HEIC, WEBP up to 120MB",
      mobileTitle: "Or upload from your mobile",
      qrTitle: "Scan the QR code",
      howToPhone: "How do I upload from my phone?",
      qrModalTitle: "Scan the QR code",
      qrModalBody:
        "Use your phone's camera to scan this QR code and upload photos directly from your mobile device",
      qrSteps: [
        "Open your phone's camera app",
        "Point it at the QR code above",
        "Select photos from your gallery or take new ones",
        "Photos will sync back to your desktop session",
      ],
      mobileUrlLabel: "Mobile Upload URL:",
      copy: "Copy",
      copied: "Copied",
      closeModal: "Close",
      keepDesktopOpen:
        "Keep the desktop session open to finish uploading your pictures.",
      mobilePageTitle: "Mobile photo upload",
      mobilePageSubtitle:
        "Select and upload photos from your phone to complete the process.",
      mobileUploadCta: "Upload photos",
      uploadingTitle: "Uploading {count} photo",
      uploadingTitlePlural: "Uploading {count} photos",
      uploadingHint: "It can take up to 1 minute to upload",
      readyTitle: "{count} photo ready to upload",
      readyTitlePlural: "{count} photos ready to upload",
      readyHint: "You can remove photos, or add more",
      sendToComputer: "Upload photos to computer",
      sending: "Sending…",
      sent: "Photos sent to your computer",
      sessionMissing:
        "This upload link is missing or expired. Scan the QR code again from your desktop.",
      removePhoto: "Remove photo",
      count: "Uploaded {count} of {max}",
      minimum: "Minimum of {min} photos",
      minimumReached: "Minimum photo requirement met",
      hoverHint: "Hover over an example to preview more",
      requirementsTitle: "Photo requirements",
      restrictionsTitle: "Photo restrictions",
      requirementGroups: [
        {
          caption: "Front-facing, eye-level",
          photos: [
            {
              src: "/onboarding/hair-length/woman-short.jpg",
              label: "Front-facing",
            },
            {
              src: "/onboarding/body-type/man-regular.jpg",
              label: "Eye-level",
            },
          ],
        },
        {
          caption: "Mix of close-up + mid-range",
          photos: [
            {
              src: "/onboarding/attire/woman-professional.jpg",
              label: "Selfie",
            },
            {
              src: "/onboarding/body-type/woman-regular.jpg",
              label: "Waist up",
            },
          ],
        },
        {
          caption: "Several outfits, backgrounds",
          photos: [
            {
              src: "/onboarding/backgrounds/man-city.jpg",
              label: "City, sweater",
            },
            {
              src: "/onboarding/attire/man-smart-casual.jpg",
              label: "Home, polo",
            },
          ],
        },
        {
          caption: "Recent, with consistent hair",
          photos: [
            {
              src: "/onboarding/attire/woman-professional.jpg",
              label: "Recent",
            },
            {
              src: "/onboarding/hair-length/woman-medium.jpg",
              label: "Neat hair",
            },
          ],
        },
      ],
      restrictionPhotos: [
        { src: "/onboarding/upload/side-profile.jpg", label: "Side profile" },
        { src: "/onboarding/upload/from-below.jpg", label: "From below" },
        { src: "/onboarding/upload/low-lighting.jpg", label: "Low lighting" },
        { src: "/onboarding/upload/ai-generated.jpg", label: "AI generated" },
        { src: "/onboarding/upload/too-close.jpg", label: "Too close" },
        { src: "/onboarding/upload/too-far.jpg", label: "Too far" },
        { src: "/onboarding/upload/swimwear.jpg", label: "Swimwear" },
        { src: "/onboarding/upload/hat-glasses.jpg", label: "Hat, glasses" },
      ],
    },
  },
  legal: {
    dataDeletion: {
      title: "Data deletion instructions",
      updated: "Last updated September 11, 2026",
      body: [
        "You can request deletion of the personal data you have provided to Perfilisto, a service operated by Tap & Swipe SAS, without signing in.",
        "1. Email hello@perfilisto.com with the subject “Perfilisto data deletion request”. Send the request from the email address associated with your Perfilisto account, if you have one.",
        "2. Tell us whether you want to delete your entire account and associated data, or specific uploaded photos or generated headshots. If you used Google or Facebook to sign in, mention the provider and the email associated with that sign-in. Do not send passwords or access tokens.",
        "3. If you no longer have access to that email address, explain this in your request so we can help identify your account. We may need to verify that the account or data belongs to you before processing deletion.",
        "Your request can include your account information, uploaded photos, generated headshots, and profile information received through Google or Facebook sign-in. Contact hello@perfilisto.com to ask about the status of your request.",
        "Removing Perfilisto from your connected apps in Google or Facebook revokes that connection, but does not itself request deletion of data already held by Perfilisto. Use the email instructions above to request deletion from Perfilisto as well.",
      ],
    },
    privacy: {
      title: "Privacy",
      updated: "Last updated September 11, 2026",
      body: [
        "Perfilisto is a headshot product operated by Tap & Swipe SAS. We process your sign-in information, reference photos and order details to provide the service.",
        "Reference photos and generated galleries are stored privately on Cloudflare. Phone-upload sessions expire after two hours. Unpaid orders expire after 24 hours. Paid reference photos and galleries are scheduled for deletion 30 days after payment.",
        "Google or Facebook provides your sign-in identifier, name, email address and profile picture where available. We use a secure session cookie to keep you signed in and your sign-in identifier to associate orders with your account.",
        "When you request photo processing, we send your reference images to OpenAI to check photographic quality and generate headshots. Whop processes payments through its secure checkout; Perfilisto does not receive your card number. We do not sell personal data. Generated results are labeled as AI generated.",
        "With your permission, we use Whop analytics to measure visits, funnel steps and advertising performance, and connect these to purchases. Whop receives your IP address and browser information; Cloudflare supplies approximate city, region, postal code and country when available. After sign-in, we also provide your account name, email address and an opaque account identifier to match your journey. We do not include reference photos, appearance answers or card details in these analytics events.",
        "Your analytics preference is stored for six months. Accepted campaign parameters are kept in your browser for up to 30 days, and a funnel identifier in the tab for up to 24 hours. Whop uses browser and device identifiers to connect events to checkout. Pending analytics events are retried in your tab for up to ten minutes and on Cloudflare for up to 24 hours. Cloudflare removes the event payload after delivery and retains a non-personal delivery marker for up to 30 days. You can withdraw permission under Tracking preferences on this page; this stops our optional analytics but does not delete previously processed events or disable essential payment processing. Contact hello@perfilisto.com for data deletion requests. We also respect browser Global Privacy Control and Do Not Track signals.",
        "You can ask us to delete your account and photos by writing to hello@perfilisto.com.",
      ],
    },
    terms: {
      title: "Terms",
      updated: "Last updated September 11, 2026",
      body: [
        "By using Perfilisto, you agree to these terms.",
        "You are responsible for the photos you upload. Only upload pictures of yourself that you have the right to use.",
        "Result photos are AI generated. The Professional plan includes a 100% money-back guarantee.",
        "We may change the product, pricing, or these terms. If a change is material, we will update this page.",
        "The service is provided by Tap & Swipe SAS. These terms are governed by the laws of France.",
      ],
    },
  },
} as const;

export type Messages = typeof en;
